steps:
- id: 'build-test-container'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/python-cloudbuild-tests', '--target', 'test-overlay', '.' ]

  # Runs the tests and generates a coverage report.
  #
  # /workspace is mounted by cloudbuild as a volume by default.
  # Therefore, changes will persist.
  #
  # You can run the linting with whichever output you need to
  # upload to sonarcloud in this fashion too.
- id: 'run-pytest'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild-tests'
  entrypoint: 'pytest'
  args: ['--cov-report=html', '--cov=.']
  waitFor: ['build-test-container']

  # Remove this: Added as an example step only, to demonstrate persistence.
- id: 'confirm'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'ls'
  args: ['-l', 'htmlcov']
  waitFor: ['run-pytest']

