steps:
- id: 'build-tests-container'
  name: 'gcr.io/kaniko-project/executor:v0.16.0'
  args: ["--dockerfile=Dockerfile",
          "--cache=true",
          "--cache-ttl=6h",
          "--destination=gcr.io/$PROJECT_ID/python-cloudbuild"]

- id: 'pipenv-install'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: 'pipenv'
  args: ['install', '--dev']
  waitFor: ['build-tests-container']

- id: 'run-pylint'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: 'pipenv'
  args: ['run', 'pylint', '**/*.py']
  waitFor: ['pipenv-install']

- id: 'run-pytest'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: 'pipenv'
  args: ['run', 'pytest', '--cov-report=html', '--cov=*']
  waitFor: ['pipenv-install']