steps:
- id: 'build-tests-container'
  name: 'gcr.io/kaniko-project/executor'
  args: ["--dockerfile=Dockerfile",
          "--cache=false",
          "--destination=gcr.io/$PROJECT_ID/python-cloudbuild"]

- id: 'pipenv-install'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: 'pipenv'
  args: ['install', '--dev']
  waitFor: ['build-tests-container']

- id: 'run-pylint'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: 'pipenv'
  args: ['run', 'pylint', '**/*.py']
  waitFor: ['pipenv-install']

- id: 'run-pytest'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: 'pipenv'
  args: ['run', 'pytest', '--cov-report=html', '--cov=*']
  waitFor: ['pipenv-install']

- id: 'upload-to-sonarcloud'
  name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=${sonarcloudLogin}'
    - '-Dsonar.projectKey=STYLER-Inc_gcloud-billing-analysis-tool'
    - '-Dsonar.organization=styler-inc'
    - '-Dsonar.sources=.'
  secretEnv: ['sonarcloudLogin']

secrets:
- kmsKeyName: projects/facy-development/locations/global/keyRings/gcloud-billing-analysis-tool-build
  secretEnv:
    sonarcloudLogin: CiQA4VLMkJlznj/3dO1t3kGXthOFpCRBHRKN6CUHM+X6pz/eiMsSUgAf4zour3S+8fyyXpztYOAhtXaw+ggvkBWTK2g+GO+ovDVkTZ7wSbaKi5xKHKxd8krYzoZwwotODxVLAC3HpT0PQe7nOAEDv4f6opTUKCpMwgQ=