steps:
- id: 'build-test-container'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/python-cloudbuild-tests', '--target', 'test-overlay', '.' ]

- id: 'run-pylint'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild-tests'
  entrypoint: 'pylint'
  args: ['/workspace/']
  waitFor: ['build-test-container']

- id: 'run-pytest'
  name: 'gcr.io/$PROJECT_ID/python-cloudbuild-tests'
  entrypoint: 'bash'
  args: ['-c', 'cd', '/workspace', '&&',
         '--cov-report=html',
         '--cov=*',
         '/workspace/']
  waitFor: ['build-test-container']
